# Generated by Django 2.0.5 on 2018-05-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.FloatField()),
                ('director', models.CharField(max_length=100)),
                ('genre', models.CharField(default='Not Available', max_length=100)),
                ('imdb_score', models.FloatField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
