# Generated by Django 2.0.4 on 2018-05-20 06:39
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_info', '0001_initial')
    ]


    operations = [
        HStoreExtension(),
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.CharField(default='Not Available', max_length=100),
        ),
    ]
