# Generated by Django 2.0.4 on 2018-05-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_info', '0001_auto_20180520_1209'),
    ]

    operations = [
    ]
