# Generated by Django 2.0.4 on 2018-05-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_info', '0002_merge_20180520_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreTypes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
