# Generated by Django 2.0.5 on 2018-05-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_info', 'populate_db'),
        ('movie_info', '0003_auto_20180520_1909'),
    ]

    operations = [
    ]
